import JSZip from "jszip";
import { SCROLL_JS } from "./gsap-layer";

export type CloneScript = { src?: string; code?: string; module?: boolean };

export type CloneResult = {
  url: string;
  title: string;
  body: string;
  bodyAttrs: string;
  css: string;
  assets: string[];
  scripts?: CloneScript[];
  stylesheets: number;
  /** Each original stylesheet as its own entry (keeps browser's per-sheet parsing). */
  styles?: string[];
  /** Original <link rel="stylesheet"> tags that couldn't be inlined (kept as fallback). */
  linkTags?: string;
  /** Whether the original site uses a framework (Next.js, Nuxt, Astro, etc.) */
  isFramework?: boolean;
};

export type Target = "static" | "vite" | "next";

const esc = (s: string) => stripLineSeparators(s).replace(/`/g, "\\`").replace(/\$\{/g, "\\${");

/** Strip unusual Unicode line separators (U+2028 LS, U+2029 PS) from output. */
function stripLineSeparators(s: string): string {
  return s.replace(/[\u2028\u2029]/g, "\n");
}

/** Re-emit the original site scripts in document order. */
function scriptTags(r: CloneResult) {
  return (r.scripts ?? [])
    .map((s) => {
      const type = s.module ? ' type="module"' : "";
      // Module scripts require CORS to load cross-origin; classic scripts must
      // NOT set crossorigin, otherwise servers without CORS headers reject them.
      const cross = s.module ? ' crossorigin="anonymous"' : "";
      if (s.src) return `<script${type} src="${s.src}"${cross}></script>`;
      return `<script${type}>${(s.code ?? "").replace(/<\/script>/gi, "<\\/script>")}</script>`;
    })
    .join("\n");
}

const linkTags = (r: CloneResult) => (r.linkTags ? `\n${r.linkTags}` : "");

/** One <style> per original stylesheet — browsers parse each independently. */
const styleBlocks = (r: CloneResult) =>
  (r.styles?.length ? r.styles : [r.css]).map((css) => `<style>\n${css}\n</style>`).join("\n");

/** <link> tags for the zip variants, one stylesheet per file. */
const styleLinks = (r: CloneResult, prefix: string) => {
  const count = r.styles?.length ?? 1;
  return Array.from(
    { length: count },
    (_, i) => `<link rel="stylesheet" href="${prefix}${i}.css" />`,
  ).join("\n");
};

export function buildPreviewHtml(r: CloneResult) {
  const fwFlag = r.isFramework ? "<script>window.__cloneIsFramework=true;</script>" : "";
  return stripLineSeparators(`<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<base href="${r.url}" />
<title>${r.title}</title>
${styleBlocks(r)}${linkTags(r)}
</head>
<body${r.bodyAttrs}>
${fwFlag}
${r.body}
${scriptTags(r)}
<script>${SCROLL_JS}</script>
</body>
</html>`);
}

/**
 * Single-file static build: styles + scroll layer inlined, exactly like the
 * preview. External CSS files would be broken by <base href> (relative paths
 * would resolve against the ORIGINAL site, not the local folder), which is why
 * the preview looked perfect but the ZIP lost its gaps.
 */
function staticHtml(r: CloneResult) {
  const fwFlag = r.isFramework ? "<script>window.__cloneIsFramework=true;</script>" : "";
  return stripLineSeparators(`<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<base href="${r.url}" />
<title>${r.title}</title>
<meta name="description" content="Cloned from ${r.url}" />
${styleBlocks(r)}${linkTags(r)}
</head>
<body${r.bodyAttrs}>
${fwFlag}
${r.body}
${scriptTags(r)}
<script>${SCROLL_JS}</script>
</body>
</html>`);
}

export async function buildZip(r: CloneResult, targets: Target[]) {
  const zip = new JSZip();
  const host = new URL(r.url).hostname.replace(/\W+/g, "-");

  zip.file(
    "README.md",
    `# Clone of ${r.url}\n\nGenerated by Site Cloner (no AI, pure fetch + rewrite).\n\nIncluded builds: ${targets.join(", ")}\n\n- \`static/\` — open \`index.html\` directly in a browser\n- \`vite/\` — \`npm install && npm run dev\`\n- \`nextjs/\` — \`npm install && npm run dev\`\n\nThe site's own scripts (GSAP, ScrollTrigger, parallax, …) are preserved so animations run exactly like the original — except un-runnable framework runtimes (Next.js/Nuxt/…), which the fallback scroll layer replaces. A lazy fallback scroll layer is embedded only when the site has no animation of its own.\n`,
  );

  if (targets.includes("static")) {
    const f = zip.folder("static")!;
    f.file("index.html", staticHtml(r));
  }

  if (targets.includes("vite")) {
    const f = zip.folder("vite")!;
    f.file(
      "package.json",
      JSON.stringify(
        {
          name: `${host}-vite-clone`,
          private: true,
          type: "module",
          scripts: { dev: "vite", build: "vite build", preview: "vite preview" },
          dependencies: { gsap: "^3.12.5" },
          devDependencies: { vite: "^5.4.0" },
        },
        null,
        2,
      ),
    );
    f.file(
      "index.html",
      stripLineSeparators(`<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>${r.title}</title>
${styleLinks(r, "/src/styles-")}${linkTags(r)}
</head>
<body${r.bodyAttrs}>
${r.body}
${scriptTags(r)}
<script type="module" src="/src/main.js"></script>
</body>
</html>`),
    );
    const src = f.folder("src")!;
    const cssParts = r.styles?.length ? r.styles : [r.css];
    cssParts.forEach((part, i) => src.file(`styles-${i}.css`, part));
    src.file(
      "main.js",
      `import gsap from "gsap";
import ScrollTrigger from "gsap/ScrollTrigger";

gsap.registerPlugin(ScrollTrigger);
window.gsap = window.gsap || gsap;
window.ScrollTrigger = window.ScrollTrigger || ScrollTrigger;

${SCROLL_JS}
`,
    );
  }

  if (targets.includes("next")) {
    const f = zip.folder("nextjs")!;
    f.file(
      "package.json",
      JSON.stringify(
        {
          name: `${host}-next-clone`,
          private: true,
          scripts: { dev: "next dev", build: "next build", start: "next start" },
          dependencies: {
            gsap: "^3.12.5",
            next: "^14.2.5",
            react: "^18.3.1",
            "react-dom": "^18.3.1",
          },
        },
        null,
        2,
      ),
    );
    f.file("next.config.mjs", `export default { images: { unoptimized: true } };\n`);
    const app = f.folder("app")!;
    const cssParts = r.styles?.length ? r.styles : [r.css];
    const cssImports = cssParts.map((_, i) => `import "./styles-${i}.css";`).join("\n");
    cssParts.forEach((part, i) => app.file(`styles-${i}.css`, part));
    app.file(
      "layout.jsx",
      `${cssImports}
export const metadata = {
  title: ${JSON.stringify(r.title)},
  description: ${JSON.stringify(`Cloned from ${r.url}`)},
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        ${r.linkTags ?? ""}
      </head>
      <body>{children}</body>
    </html>
  );
}
`,
    );
    app.file(
      "page.jsx",
      `import OriginalScripts from "./OriginalScripts";

const MARKUP = \`${esc(r.body)}\`;

export default function Page() {
  return (
    <>
      <div dangerouslySetInnerHTML={{ __html: MARKUP }} />
      <OriginalScripts />
    </>
  );
}
`,
    );
    app.file("scripts.json", JSON.stringify(r.scripts ?? [], null, 2));
    app.file(
      "OriginalScripts.jsx",
      `"use client";

import { useEffect } from "react";
import gsap from "gsap";
import ScrollTrigger from "gsap/ScrollTrigger";
import SCRIPTS from "./scripts.json";

// Loads the original site scripts (GSAP, ScrollTrigger, parallax, marquee,
// SVG draw, …) in document order so the clone animates like the source.
export default function OriginalScripts() {
  useEffect(() => {
    let cancelled = false;
    gsap.registerPlugin(ScrollTrigger);
    window.gsap = window.gsap || gsap;
    window.ScrollTrigger = window.ScrollTrigger || ScrollTrigger;
    window.__cloneOriginalScripts = true;

    const added = [];
    async function run() {
      for (const s of SCRIPTS) {
        if (cancelled) return;
        await new Promise((resolve) => {
          const el = document.createElement("script");
          if (s.module) el.type = "module";
          if (s.src) {
            el.src = s.src;
            if (s.module) el.crossOrigin = "anonymous";
            el.onload = resolve;
            el.onerror = resolve;
          } else {
            el.textContent = s.code || "";
          }
          document.body.appendChild(el);
          added.push(el);
          if (!s.src) resolve();
        });
      }
      window.dispatchEvent(new Event("load"));
      setTimeout(() => ScrollTrigger.refresh(), 1200);
    }
    run();

    return () => {
      cancelled = true;
      added.forEach((el) => el.remove());
    };
  }, []);
  return null;
}
`,
    );
  }

  return await zip.generateAsync({ type: "blob" });
}
