import JSZip from "jszip";
import { SCROLL_JS } from "./gsap-layer";

export type CloneScript = { src?: string; code?: string; module?: boolean };

export type CloneResult = {
  url: string;
  title: string;
  body: string;
  bodyAttrs: string;
  css: string;
  assets: string[];
  scripts?: CloneScript[];
  stylesheets: number;
};

export type Target = "static" | "vite" | "next";

const esc = (s: string) => s.replace(/`/g, "\\`").replace(/\$\{/g, "\\${");

/** Re-emit the original site scripts in document order. */
function scriptTags(r: CloneResult) {
  return (r.scripts ?? [])
    .map((s) => {
      const type = s.module ? ' type="module"' : "";
      if (s.src) return `<script${type} src="${s.src}" crossorigin="anonymous"></script>`;
      return `<script${type}>${(s.code ?? "").replace(/<\/script>/gi, "<\\/script>")}</script>`;
    })
    .join("\n");
}

const FALLBACK_TAGS = `<script>window.__cloneOriginalScripts = true;</script>
<script src="https://cdn.jsdelivr.net/npm/gsap@3.12.5/dist/gsap.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/gsap@3.12.5/dist/ScrollTrigger.min.js"></script>`;

export function buildPreviewHtml(r: CloneResult) {
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<base href="${r.url}" />
<title>${r.title}</title>
<style>${r.css}</style>
</head>
<body${r.bodyAttrs}>
${r.body}
${scriptTags(r)}
${FALLBACK_TAGS}
<script>${SCROLL_JS}</script>
</body>
</html>`;
}

function staticHtml(r: CloneResult) {
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<base href="${r.url}" />
<title>${r.title}</title>
<meta name="description" content="Cloned from ${r.url}" />
<link rel="stylesheet" href="./styles.css" />
</head>
<body${r.bodyAttrs}>
${r.body}
${scriptTags(r)}
${FALLBACK_TAGS}
<script src="./scroll.js"></script>
</body>
</html>`;
}


export async function buildZip(r: CloneResult, targets: Target[]) {
  const zip = new JSZip();
  const host = new URL(r.url).hostname.replace(/\W+/g, "-");

  zip.file(
    "README.md",
    `# Clone of ${r.url}\n\nGenerated by Site Cloner (no AI, pure fetch + rewrite).\n\nIncluded builds: ${targets.join(", ")}\n\n- \`static/\` — open \`index.html\` directly in a browser\n- \`vite/\` — \`npm install && npm run dev\`\n- \`nextjs/\` — \`npm install && npm run dev\`\n\nGSAP ScrollTrigger reveal animations are wired in \`scroll.js\` / \`ScrollAnimations\`.\n`,
  );

  if (targets.includes("static")) {
    const f = zip.folder("static")!;
    f.file("index.html", staticHtml(r));
    f.file("styles.css", r.css);
    f.file("scroll.js", SCROLL_JS);
  }

  if (targets.includes("vite")) {
    const f = zip.folder("vite")!;
    f.file(
      "package.json",
      JSON.stringify(
        {
          name: `${host}-vite-clone`,
          private: true,
          type: "module",
          scripts: { dev: "vite", build: "vite build", preview: "vite preview" },
          dependencies: { gsap: "^3.12.5" },
          devDependencies: { vite: "^5.4.0" },
        },
        null,
        2,
      ),
    );
    f.file(
      "index.html",
      `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<base href="${r.url}" />
<title>${r.title}</title>
<link rel="stylesheet" href="/src/styles.css" />
</head>
<body${r.bodyAttrs}>
${r.body}
${scriptTags(r)}
${FALLBACK_TAGS}
<script type="module" src="/src/main.js"></script>
</body>
</html>`,
    );
    const src = f.folder("src")!;
    src.file("styles.css", r.css);
    src.file(
      "main.js",
      `import gsap from "gsap";
import ScrollTrigger from "gsap/ScrollTrigger";

gsap.registerPlugin(ScrollTrigger);
window.gsap = window.gsap || gsap;
window.ScrollTrigger = window.ScrollTrigger || ScrollTrigger;

${SCROLL_JS}
`,

    );
  }

  if (targets.includes("next")) {
    const f = zip.folder("nextjs")!;
    f.file(
      "package.json",
      JSON.stringify(
        {
          name: `${host}-next-clone`,
          private: true,
          scripts: { dev: "next dev", build: "next build", start: "next start" },
          dependencies: {
            gsap: "^3.12.5",
            next: "^14.2.5",
            react: "^18.3.1",
            "react-dom": "^18.3.1",
          },
        },
        null,
        2,
      ),
    );
    f.file("next.config.mjs", `export default { images: { unoptimized: true } };\n`);
    const app = f.folder("app")!;
    app.file("globals.css", r.css);
    app.file(
      "layout.jsx",
      `import "./globals.css";

export const metadata = {
  title: ${JSON.stringify(r.title)},
  description: ${JSON.stringify(`Cloned from ${r.url}`)},
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <base href=${JSON.stringify(r.url)} />
      </head>
      <body>{children}</body>
    </html>
  );
}
`,
    );
    app.file(
      "page.jsx",
      `import OriginalScripts from "./OriginalScripts";

const MARKUP = \`${esc(r.body)}\`;

export default function Page() {
  return (
    <>
      <div dangerouslySetInnerHTML={{ __html: MARKUP }} />
      <OriginalScripts />
    </>
  );
}
`,
    );
    app.file(
      "scripts.json",
      JSON.stringify(r.scripts ?? [], null, 2),
    );
    app.file(
      "OriginalScripts.jsx",
      `"use client";

import { useEffect } from "react";
import gsap from "gsap";
import ScrollTrigger from "gsap/ScrollTrigger";
import SCRIPTS from "./scripts.json";

// Loads the original site scripts (GSAP, ScrollTrigger, parallax, marquee,
// SVG draw, …) in document order so the clone animates like the source.
export default function OriginalScripts() {
  useEffect(() => {
    let cancelled = false;
    gsap.registerPlugin(ScrollTrigger);
    window.gsap = window.gsap || gsap;
    window.ScrollTrigger = window.ScrollTrigger || ScrollTrigger;
    window.__cloneOriginalScripts = true;

    const added = [];
    async function run() {
      for (const s of SCRIPTS) {
        if (cancelled) return;
        await new Promise((resolve) => {
          const el = document.createElement("script");
          if (s.module) el.type = "module";
          if (s.src) {
            el.src = s.src;
            el.crossOrigin = "anonymous";
            el.onload = resolve;
            el.onerror = resolve;
          } else {
            el.textContent = s.code || "";
          }
          document.body.appendChild(el);
          added.push(el);
          if (!s.src) resolve();
        });
      }
      window.dispatchEvent(new Event("load"));
      setTimeout(() => ScrollTrigger.refresh(), 1200);
    }
    run();

    return () => {
      cancelled = true;
      added.forEach((el) => el.remove());
    };
  }, []);
  return null;
}
`,
    );

  }

  return await zip.generateAsync({ type: "blob" });
}
