import JSZip from "jszip";
import { SCROLL_JS } from "./gsap-layer";

export type CloneResult = {
  url: string;
  title: string;
  body: string;
  bodyAttrs: string;
  css: string;
  assets: string[];
  stylesheets: number;
};

export type Target = "static" | "vite" | "next";

const esc = (s: string) => s.replace(/`/g, "\\`").replace(/\$\{/g, "\\${");

export function buildPreviewHtml(r: CloneResult) {
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<base href="${r.url}" />
<title>${r.title}</title>
<style>${r.css}</style>
</head>
<body${r.bodyAttrs}>
${r.body}
<script src="https://cdn.jsdelivr.net/npm/gsap@3.12.5/dist/gsap.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/gsap@3.12.5/dist/ScrollTrigger.min.js"></script>
<script>${SCROLL_JS}</script>
</body>
</html>`;
}

function staticHtml(r: CloneResult) {
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>${r.title}</title>
<meta name="description" content="Cloned from ${r.url}" />
<link rel="stylesheet" href="./styles.css" />
</head>
<body${r.bodyAttrs}>
${r.body}
<script src="https://cdn.jsdelivr.net/npm/gsap@3.12.5/dist/gsap.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/gsap@3.12.5/dist/ScrollTrigger.min.js"></script>
<script src="./scroll.js"></script>
</body>
</html>`;
}

export async function buildZip(r: CloneResult, targets: Target[]) {
  const zip = new JSZip();
  const host = new URL(r.url).hostname.replace(/\W+/g, "-");

  zip.file(
    "README.md",
    `# Clone of ${r.url}\n\nGenerated by Site Cloner (no AI, pure fetch + rewrite).\n\nIncluded builds: ${targets.join(", ")}\n\n- \`static/\` — open \`index.html\` directly in a browser\n- \`vite/\` — \`npm install && npm run dev\`\n- \`nextjs/\` — \`npm install && npm run dev\`\n\nGSAP ScrollTrigger reveal animations are wired in \`scroll.js\` / \`ScrollAnimations\`.\n`,
  );

  if (targets.includes("static")) {
    const f = zip.folder("static")!;
    f.file("index.html", staticHtml(r));
    f.file("styles.css", r.css);
    f.file("scroll.js", SCROLL_JS);
  }

  if (targets.includes("vite")) {
    const f = zip.folder("vite")!;
    f.file(
      "package.json",
      JSON.stringify(
        {
          name: `${host}-vite-clone`,
          private: true,
          type: "module",
          scripts: { dev: "vite", build: "vite build", preview: "vite preview" },
          dependencies: { gsap: "^3.12.5" },
          devDependencies: { vite: "^5.4.0" },
        },
        null,
        2,
      ),
    );
    f.file(
      "index.html",
      `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>${r.title}</title>
<link rel="stylesheet" href="/src/styles.css" />
<script type="module" src="/src/main.js"></script>
</head>
<body${r.bodyAttrs}>
${r.body}
</body>
</html>`,
    );
    const src = f.folder("src")!;
    src.file("styles.css", r.css);
    src.file(
      "main.js",
      `import gsap from "gsap";
import ScrollTrigger from "gsap/ScrollTrigger";

gsap.registerPlugin(ScrollTrigger);
window.gsap = gsap;
window.ScrollTrigger = ScrollTrigger;

${SCROLL_JS}
`,
    );
  }

  if (targets.includes("next")) {
    const f = zip.folder("nextjs")!;
    f.file(
      "package.json",
      JSON.stringify(
        {
          name: `${host}-next-clone`,
          private: true,
          scripts: { dev: "next dev", build: "next build", start: "next start" },
          dependencies: {
            gsap: "^3.12.5",
            next: "^14.2.5",
            react: "^18.3.1",
            "react-dom": "^18.3.1",
          },
        },
        null,
        2,
      ),
    );
    f.file("next.config.mjs", `export default { images: { unoptimized: true } };\n`);
    const app = f.folder("app")!;
    app.file("globals.css", r.css);
    app.file(
      "layout.jsx",
      `import "./globals.css";

export const metadata = {
  title: ${JSON.stringify(r.title)},
  description: ${JSON.stringify(`Cloned from ${r.url}`)},
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`,
    );
    app.file(
      "page.jsx",
      `import ScrollAnimations from "./ScrollAnimations";

const MARKUP = \`${esc(r.body)}\`;

export default function Page() {
  return (
    <>
      <ScrollAnimations />
      <div dangerouslySetInnerHTML={{ __html: MARKUP }} />
    </>
  );
}
`,
    );
    app.file(
      "ScrollAnimations.jsx",
      `"use client";

import { useEffect } from "react";
import gsap from "gsap";
import ScrollTrigger from "gsap/ScrollTrigger";

export default function ScrollAnimations() {
  useEffect(() => {
    gsap.registerPlugin(ScrollTrigger);
    const ctx = gsap.context(() => {
      document
        .querySelectorAll("section, header, footer, article, .clone-reveal")
        .forEach((el) => {
          gsap.from(el, {
            opacity: 0,
            y: 48,
            duration: 0.9,
            ease: "power3.out",
            scrollTrigger: { trigger: el, start: "top 85%", toggleActions: "play none none reverse" },
          });
        });
      document.querySelectorAll("h1, h2, h3").forEach((el) => {
        gsap.from(el, {
          opacity: 0,
          y: 24,
          duration: 0.7,
          ease: "power2.out",
          scrollTrigger: { trigger: el, start: "top 90%" },
        });
      });
    });
    return () => ctx.revert();
  }, []);
  return null;
}
`,
    );
  }

  return await zip.generateAsync({ type: "blob" });
}
