export const GSAP_SNIPPET = `
<script src="https://cdn.jsdelivr.net/npm/gsap@3.12.5/dist/gsap.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/gsap@3.12.5/dist/ScrollTrigger.min.js"></script>
<script src="./scroll.js" defer></script>
`;

export const SCROLL_JS = `/* GSAP ScrollTrigger layer generated by Site Cloner */
(function () {
  function init() {
    if (!window.gsap || !window.ScrollTrigger) return;
    gsap.registerPlugin(ScrollTrigger);

    var vh = window.innerHeight;

    function animatable(el) {
      if (!el || el.dataset.cloneAnimated) return false;
      var r = el.getBoundingClientRect();
      // skip invisible, zero-size and page-sized wrappers
      if (r.height < 24 || r.height > vh * 4) return false;
      if (el.closest("[data-clone-animated]") && el.dataset.cloneAnimated !== "root") return false;
      return true;
    }

    var blocks = Array.prototype.slice
      .call(
        document.querySelectorAll(
          "body section, body header, body footer, body article, body main > div, body .clone-reveal"
        )
      )
      .filter(animatable);

    blocks.forEach(function (el) {
      el.dataset.cloneAnimated = "root";
      // fromTo guarantees the element ends fully visible even if the
      // trigger never fires (short pages, resized viewports, print, etc.)
      gsap.fromTo(
        el,
        { opacity: 0, y: 40 },
        {
          opacity: 1,
          y: 0,
          duration: 0.9,
          ease: "power3.out",
          immediateRender: false,
          overwrite: "auto",
          scrollTrigger: { trigger: el, start: "top 92%", once: true }
        }
      );
    });

    document.querySelectorAll("h1, h2, h3").forEach(function (el) {
      if (!animatable(el)) return;
      gsap.fromTo(
        el,
        { opacity: 0, y: 20 },
        {
          opacity: 1,
          y: 0,
          duration: 0.7,
          ease: "power2.out",
          immediateRender: false,
          overwrite: "auto",
          scrollTrigger: { trigger: el, start: "top 95%", once: true }
        }
      );
    });

    // Recalculate once images/fonts settle, otherwise triggers measure a
    // shorter page and sections below the fold stay stuck at opacity 0.
    window.addEventListener("load", function () {
      ScrollTrigger.refresh();
    });
    setTimeout(function () {
      ScrollTrigger.refresh();
    }, 1200);

    // Safety net: anything still invisible after 3s gets forced visible.
    setTimeout(function () {
      document.querySelectorAll("[data-clone-animated]").forEach(function (el) {
        if (parseFloat(getComputedStyle(el).opacity) < 0.05) {
          gsap.set(el, { clearProps: "all" });
        }
      });
    }, 3000);
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", init);
  } else {
    init();
  }
})();
`;
